apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.ns }}
  annotations:
    kompose.cmd: kompose convert -f k8s/docker-compose.yml -o k8s/base
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysql-server
